# Cubic with discretized derivatives

In [173]:
using SymPy

@syms x Δ δ
xs = [
    symbols("x_{i-1}"),
    symbols("x_{i}"),
    symbols("x_{i+1}"),
    symbols("x_{i+2}"),
]
xs = [i*Δ for i in -1:2]
ys = [
    symbols("y_{i-1}"),
    symbols("y_{i}"),
    symbols("y_{i+1}"),
    symbols("y_{i+2}"),
]
cs = [symbols("c_{$i}") for i in 0:3]


4-element Vector{Sym}:
 c_{0}
 c_{1}
 c_{2}
 c_{3}

# General case

In [114]:
cubic_pol = sum(symbols("c_{$i}")*x^i for i in 0:3)
eqs = [
    cubic_pol.subs(x,xs[2] - xs[2]) - ys[2], # f(0)
    cubic_pol.subs(x,xs[3] - xs[2]) - ys[3], # f(Δ)
    cubic_pol.diff(x).subs(x,xs[2] - xs[2]) - (ys[3] - ys[1])/(xs[3] - xs[1]),# f'(0)
    cubic_pol.diff(x).subs(x,xs[3] - xs[2]) - (ys[4] - ys[2])/(xs[4] - xs[2]) # f'(Δ)
]
eqs = expand.(eqs)

sol = solve(eqs,cs)
appr = cubic_pol.subs(sol) |> expand

for y in ys
    appr.coeff(y).subs(x/Δ,δ) |> display
end

   3         
  δ     2   δ
- ── + δ  - ─
  2         2

   3      2    
3⋅δ    5⋅δ     
──── - ──── + 1
 2      2      

     3           
  3⋅δ       2   δ
- ──── + 2⋅δ  + ─
   2            2

 3    2
δ    δ 
── - ──
2    2 

# Near endpoints

In [123]:
##Beginning

# m = 1 ## Assuming explicit derivative in the beginning
m = 2 ## Midpoint approximated with the same end value
m = 3//2 ## Mean of the 2 approaches

eqs = [
    cubic_pol.subs(x,xs[2] - xs[2]) - ys[2], # f(0)
    cubic_pol.subs(x,xs[3] - xs[2]) - ys[3], # f(Δ)
    cubic_pol.diff(x).subs(x,xs[2] - xs[2]) - (ys[3] - ys[2])/(m*(xs[3] - xs[2])),# f'(0)
    cubic_pol.diff(x).subs(x,xs[3] - xs[2]) - (ys[4] - ys[2])/(xs[4] - xs[2]) # f'(Δ)
]
eqs = expand.(eqs)

sol = solve(eqs,cs)
appr = cubic_pol.subs(sol) |> expand

for y in ys
    appr.coeff(y).subs(x/Δ,δ) |> display
end

0

   3      2          
5⋅δ    7⋅δ    2⋅δ    
──── - ──── - ─── + 1
 6      6      3     

     3      2      
  4⋅δ    5⋅δ    2⋅δ
- ──── + ──── + ───
   3      3      3 

 3    2
δ    δ 
── - ──
2    2 

In [172]:
##End
m = 1 ## Assuming explicit derivative in the beginning
# m = 2 ## Midpoint approximated with the same end value
# m = 3//2 ## Mean of the 2 approaches

eqs = [
    cubic_pol.subs(x,xs[2] - xs[2]) - ys[2], # f(0)
    cubic_pol.subs(x,xs[3] - xs[2]) - ys[3], # f(Δ)
    cubic_pol.diff(x).subs(x,xs[2] - xs[2]) - (ys[3] - ys[1])/((xs[3] - xs[1])),# f'(0)
    cubic_pol.diff(x).subs(x,xs[3] - xs[2]) - (ys[3] - ys[2])/(m*(xs[3] - xs[2])) # f'(Δ)
]
eqs = expand.(eqs)

sol = solve(eqs,cs)
appr = cubic_pol.subs(sol) |> expand

for y in ys
    appr.coeff(y).subs(x/Δ,δ) |> display
end

   3         
  δ     2   δ
- ── + δ  - ─
  2         2

 3      2    
δ  - 2⋅δ  + 1

   3         
  δ     2   δ
- ── + δ  + ─
  2         2

0

In [178]:
##Beginning Not enforcing unknown conditions
quad_pol = sum(symbols("c_{$i}")*x^i for i in 0:2)
eqs = [
    quad_pol.subs(x,xs[2] - xs[2]) - ys[2], # f(0)
    quad_pol.subs(x,xs[3] - xs[2]) - ys[3], # f(Δ)
    quad_pol.diff(x).subs(x,xs[3] - xs[2]) - (ys[4] - ys[2])/(xs[4] - xs[2]) # f'(Δ)
]
eqs = expand.(eqs)

sol = solve(eqs,cs)
appr = quad_pol.subs(sol) |> expand

for y in ys
    appr.coeff(y).subs(x/Δ,δ) |> display
end

0

 2          
δ    3⋅δ    
── - ─── + 1
2     2     

   2      
- δ  + 2⋅δ

 2    
δ    δ
── - ─
2    2

In [179]:
##End Not enforcing unknown conditions
quad_pol = sum(symbols("c_{$i}")*x^i for i in 0:2)

eqs = [
    quad_pol.subs(x,xs[2] - xs[2]) - ys[2], # f(0)
    quad_pol.subs(x,xs[3] - xs[2]) - ys[3], # f(Δ)
    quad_pol.diff(x).subs(x,xs[2] - xs[2]) - (ys[3] - ys[1])/((xs[3] - xs[1])),# f'(0)
]
eqs = expand.(eqs)

sol = solve(eqs,cs)
appr = quad_pol.subs(sol) |> expand

for y in ys
    appr.coeff(y).subs(x/Δ,δ) |> display
end

 2    
δ    δ
── - ─
2    2

     2
1 - δ 

 2    
δ    δ
── + ─
2    2

0

# Cubic with Lagrangian polynomials

In [38]:
using SymPy

@syms x Δ δ

(x, Δ, δ)

In [40]:
idxs = -1:2
xs = [i*Δ for i in idxs]
ys = [symbols("y_{$i}") for i in idxs]

4-element Vector{Sym}:
 y_{-1}
  y_{0}
  y_{1}
  y_{2}

In [42]:
p(j,xs = xs) = prod((x-xs[k])/(xs[j]-xs[k]) for k in 1:length(xs) if k != j)

p (generic function with 2 methods)

In [43]:
for i in 1:length(xs)
    p(i).expand().subs(x/Δ, δ) |> display
end

   3    2    
  δ    δ    δ
- ── + ── - ─
  6    2    3

 3             
δ     2   δ    
── - δ  - ─ + 1
2         2    

   3    2    
  δ    δ     
- ── + ── + δ
  2    2     

 3    
δ    δ
── - ─
6    6

## Connecting piecewise LP-s

In [52]:
idxs = -1:2
xs0 = [i*Δ for i in idxs]
ys0 = [symbols("y_{$i}") for i in idxs]

idxs = -0:3
xs1 = [i*Δ for i in idxs]
ys1 = [symbols("y_{$i}") for i in idxs]

4-element Vector{Sym}:
 y_{0}
 y_{1}
 y_{2}
 y_{3}

In [64]:
pol0 = sum(y*p(j,xs0) for (j,y) in enumerate(ys0)).expand()#.subs(x/Δ, δ)
pol1 = sum(y*p(j,xs1) for (j,y) in enumerate(ys1)).expand()#.subs(x/Δ, δ);
display(pol0)
display(pol1)

   3           3          3          3          2           2          2      
  x ⋅y_{-1}   x ⋅y_{0}   x ⋅y_{1}   x ⋅y_{2}   x ⋅y_{-1}   x ⋅y_{0}   x ⋅y_{1}
- ───────── + ──────── - ──────── + ──────── + ───────── - ──────── + ────────
        3          3          3          3           2         2           2  
     6⋅Δ        2⋅Δ        2⋅Δ        6⋅Δ         2⋅Δ         Δ         2⋅Δ   

                                                 
   x⋅y_{-1}   x⋅y_{0}   x⋅y_{1}   x⋅y_{2}        
 - ──────── - ─────── + ─────── - ─────── + y_{0}
     3⋅Δ        2⋅Δ        Δ        6⋅Δ          
                                                 

   3          3          3          3          2            2            2    
  x ⋅y_{0}   x ⋅y_{1}   x ⋅y_{2}   x ⋅y_{3}   x ⋅y_{0}   5⋅x ⋅y_{1}   2⋅x ⋅y_{
- ──────── + ──────── - ──────── + ──────── + ──────── - ────────── + ────────
       3          3          3          3         2            2           2  
    6⋅Δ        2⋅Δ        2⋅Δ        6⋅Δ         Δ          2⋅Δ           Δ   

      2                                                             
2}   x ⋅y_{3}   11⋅x⋅y_{0}   3⋅x⋅y_{1}   3⋅x⋅y_{2}   x⋅y_{3}        
── - ──────── - ────────── + ───────── - ───────── + ─────── + y_{0}
          2        6⋅Δ           Δ          2⋅Δ        3⋅Δ          
       2⋅Δ                                                          

In [65]:
pol0.subs(x,Δ) - pol1.subs(x,Δ)

0

In [66]:
pol0.diff(x).subs(x,Δ) - pol1.diff(x).subs(x,Δ)

y_{-1}   2⋅y_{0}   y_{1}   2⋅y_{2}   y_{3}
────── - ─────── + ───── - ─────── + ─────
 6⋅Δ       3⋅Δ       Δ       3⋅Δ      6⋅Δ 

In [67]:
pol0.diff(x,2).subs(x,Δ) - pol1.diff(x,2).subs(x,Δ)

0

In [59]:
xs0|>display
xs1|>display

4-element Vector{Sym}:
  -Δ
   0
   Δ
 2⋅Δ

4-element Vector{Sym}:
   0
   Δ
 2⋅Δ
 3⋅Δ

# Fifth order polynomial interpolation

In [1]:
using SymPy

@syms x Δ δ
xs = [i*Δ for i in -1:2]
ys = [
    symbols("y_{i-1}"),
    symbols("y_{i}"),
    symbols("y_{i+1}"),
    symbols("y_{i+2}"),
]
cs = [symbols("c_{$i}") for i in 0:5]

6-element Vector{Sym}:
 c_{0}
 c_{1}
 c_{2}
 c_{3}
 c_{4}
 c_{5}

In [2]:
disc_diff(i, ys = ys) = (ys[i+1] - ys[i-1])/(2Δ)
disc_diff2(i, ys = ys) = (ys[i+1] -2*ys[i] + ys[i-1])/(Δ^2)

disc_diff2 (generic function with 2 methods)

In [3]:
quintic_pol = sum(symbols("c_{$i}")*x^i for i in 0:5)
eqs = [
    quintic_pol.subs(x,xs[2]) - ys[2], # f(0)
    quintic_pol.subs(x,xs[3]) - ys[3], # f(Δ)
    quintic_pol.diff(x).subs(x,xs[2]) - disc_diff(2,ys),# f'(0)
    quintic_pol.diff(x).subs(x,xs[3]) - disc_diff(3,ys), # f'(Δ)
    quintic_pol.diff(x,2).subs(x,xs[2]) - disc_diff2(2,ys),# f''(0)
    quintic_pol.diff(x,2).subs(x,xs[3]) - disc_diff2(3,ys), # f''(Δ)
]
eqs = expand.(eqs)

sol = solve(eqs,cs)
appr = quintic_pol.subs(sol) |> expand

for y in ys
    appr.coeff(y).subs(x/Δ,δ) |> display
end

        4      3    2    
 5   5⋅δ    3⋅δ    δ    δ
δ  - ──── + ──── + ── - ─
      2      2     2    2

             4      3         
     5   15⋅δ    9⋅δ     2    
- 3⋅δ  + ───── - ──── - δ  + 1
           2      2           

           4      3    2    
   5   15⋅δ    9⋅δ    δ    δ
3⋅δ  - ───── + ──── + ── + ─
         2      2     2    2

          4      3
   5   5⋅δ    3⋅δ 
- δ  + ──── - ────
        2      2  

┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
│   caller = npyinitialize() at numpy.jl:67
└ @ PyCall /home/htsykora/.julia/packages/PyCall/3fwVL/src/numpy.jl:67


In [4]:
# Beginning: not enforcing unknown conditions
cubic_pol = sum(symbols("c_{$i}")*x^i for i in 0:3)
eqs = [
    cubic_pol.subs(x,xs[2]) - ys[2], # f(0)
    cubic_pol.subs(x,xs[3]) - ys[3], # f(Δ)
    cubic_pol.diff(x).subs(x,xs[3]) - disc_diff(3,ys), # f'(Δ)
    cubic_pol.diff(x,2).subs(x,xs[3]) - disc_diff2(3,ys), # f''(Δ)
]
eqs = expand.(eqs)

sol = solve(eqs,cs)
appr = cubic_pol.subs(sol) |> expand

for y in ys
    appr.coeff(y).subs(x/Δ,δ) |> display
end

0

 2          
δ    3⋅δ    
── - ─── + 1
2     2     

   2      
- δ  + 2⋅δ

 2    
δ    δ
── - ─
2    2

In [7]:
# End: not enforcing unknown conditions
cubic_pol = sum(symbols("c_{$i}")*x^i for i in 0:3)
eqs = [
    cubic_pol.subs(x,xs[2]) - ys[2], # f(0)
    cubic_pol.subs(x,xs[3]) - ys[3], # f(Δ)
    cubic_pol.diff(x).subs(x,xs[2]) - disc_diff(2,ys),# f'(0)
    cubic_pol.diff(x,2).subs(x,xs[2]) - disc_diff2(2,ys),# f''(0)
]
eqs = expand.(eqs)

sol = solve(eqs, cs)
appr = cubic_pol.subs(sol) |> expand

for y in ys
    appr.coeff(y).subs(x/Δ,δ) |> display
end

 2    
δ    δ
── - ─
2    2

     2
1 - δ 

 2    
δ    δ
── + ─
2    2

0

In [9]:
cubic_pol

                         2          3
c_{0} + c_{1}⋅x + c_{2}⋅x  + c_{3}⋅x 

In [11]:
eqs

4-element Vector{Sym}:
                                     c_{0} - y_{i}
 c_{0} + c_{1}*Δ + c_{2}*Δ^2 + c_{3}*Δ^3 - y_{i+1}
             c_{1} - y_{i+1}/(2*Δ) + y_{i-1}/(2*Δ)
 2*c_{2} - y_{i+1}/Δ^2 - y_{i-1}/Δ^2 + 2*y_{i}/Δ^2

In [12]:
sol

Dict{Any, Any} with 4 entries:
  c_{1} => (y_{i+1} - y_{i-1})/(2*Δ)
  c_{2} => (y_{i+1} + y_{i-1} - 2*y_{i})/(2*Δ^2)
  c_{3} => 0
  c_{0} => y_{i}